baseURL = "https://example.com"
languageCode = "en-us"
title = "Example YinYong Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[menus]
[[menus.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menus.main]]
  name = "Categories"
  url = "/categories/"
  weight = 3

[params]
disqus = "joway" # disqus account name
extraHead = ''
mainSections = ["posts"]
author = "Yinyang"

[[params.socials]]
name = "RSS"
link = "/index.xml"
